### ISSUE TITLE
how to add multiple users?

### ISSUE THREAD

**Issue by bumansu** [andrewfromtver/xray-shadowsocks-vless#1]

**Comment by andrewfromtver** [comment]
Hello.

If you want to add multiple users
* run `./deploy.sh uuid` to generate id for new user, you will get something like `a48061f3-605a-4b55-8081-60b4a76f6f45`
* run `docker exec -it xray-shadowsocks-vless vi /opt/xray/config.json` to open xray server config in container
* add new clients to config file as follow and save config file
```
{
      "port": 443,
      "protocol": "vless",
      "tag": "vless_tls",
      "settings": {
        "clients": [
          {
            "id": "e2419701-1d0f-4448-96bd-968a65f46df7",
            "email": "username1@domain.com",
            "flow": "xtls-rprx-vision"
          },
          {
            "id": "a48061f3-605a-4b55-8081-60b4a76f6f45",
            "email": "username2@domain.com",
            "flow": "xtls-rprx-vision"
          },
          {
            "id": "651c0203-9b0d-4922-8a88-a5f8eada426f",
            "email": "username3@domain.com",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
},
```
* run `./deploy.sh restart` to apply new settings

**Comment by andrewfromtver** [comment]
@bumansu Сan I close this issue?

**Comment by andrewfromtver** [comment]
It means, that you make a mistake in `config.json` file and container crashes with provided wrong settings, make sure that JSON file is correct and you use different `id` for new users.

**Comment by andrewfromtver** [comment]
Unfortunately, the script cannot output more than one line yet, in order to get links for new users, you can simply change the UUID in original one.
For example in `vless://7c7703a4-60cf-4525-b4be-06e76df73a8f@[ip-address]:[port]?security=reality...` the UUID is `7c7703a4-60cf-4525-b4be-06e76df73a8f` and if you want to get new URLs - you can just modify original URL for each user like this.

**Comment by bumansu** [comment]
Ok, thank you very much! 
спасибо!
